x-common: &common
  environment:
    KAFKA_BROKERS: kafka:29092
    USER_SERVER_ADDRESS: user-service:50051
    SESSION_SERVER_ADDRESS: session-service:50052
    TRANSACTION_SERVER_ADDRESS: transaction-service:50053
    AUTH_SERVER_ADDRESS: auth-service:50054
  networks:
    - beerbux-net

services:
  auth-service:
    build:
      context: ./auth-service
    ports:
      - "50054:50054"
    <<: *common

  user-service:
    build:
      context: ./user-service
    ports:
      - "50051:50051"
    <<: *common

  session-service:
    build:
      context: ./session-service
    ports:
      - "50052:50052"
    <<: *common

  transaction-service:
    build:
      context: ./transaction-service
    ports:
      - "50053:50053"
    <<: *common

  ledger-service:
    build:
      context: ./ledger-service
    <<: *common

  stream-service:
    build:
      context: ./stream-service
    ports:
      - "50057:50057"
    <<: *common

  gateway-api:
    build:
      context: ./gateway-api
    ports:
      - "42069:42069"
    profiles:
      - gateway
    <<: *common

networks:
  beerbux-net:
    name: beerbux-net
    external: false
