// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const addMemberToSession = `-- name: AddMemberToSession :exec
insert into session_members (session_id, member_id, is_admin)
values ($1, $2, $3)
on conflict(session_id, member_id) do update
set is_deleted = false
`

type AddMemberToSessionParams struct {
	SessionID uuid.UUID
	MemberID  uuid.UUID
	IsAdmin   bool
}

func (q *Queries) AddMemberToSession(ctx context.Context, arg AddMemberToSessionParams) error {
	_, err := q.db.ExecContext(ctx, addMemberToSession, arg.SessionID, arg.MemberID, arg.IsAdmin)
	return err
}

const countSessionAdminMembers = `-- name: CountSessionAdminMembers :one
select count(*) from session_members where session_id = $1 and is_admin = true
`

func (q *Queries) CountSessionAdminMembers(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessionAdminMembers, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSessionMembers = `-- name: CountSessionMembers :one
select count(*) from session_members where session_id = $1 and is_deleted = false
`

func (q *Queries) CountSessionMembers(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessionMembers, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSessionMembersIncludingDeleted = `-- name: CountSessionMembersIncludingDeleted :one
select count(*) from session_members where session_id = $1
`

func (q *Queries) CountSessionMembersIncludingDeleted(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessionMembersIncludingDeleted, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
insert into sessions (name, creator_id) values ($1, $2) returning id, name, is_active, creator_id, created_at, updated_at
`

type CreateSessionParams struct {
	Name      string
	CreatorID uuid.UUID
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.Name, arg.CreatorID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSessionHistory = `-- name: CreateSessionHistory :exec
insert into session_history (session_id, member_id, event_type, event_data)
values ($1, $2, $3, $4)
`

type CreateSessionHistoryParams struct {
	SessionID uuid.UUID
	MemberID  uuid.UUID
	EventType string
	EventData pqtype.NullRawMessage
}

func (q *Queries) CreateSessionHistory(ctx context.Context, arg CreateSessionHistoryParams) error {
	_, err := q.db.ExecContext(ctx, createSessionHistory,
		arg.SessionID,
		arg.MemberID,
		arg.EventType,
		arg.EventData,
	)
	return err
}

const deleteSessionMember = `-- name: DeleteSessionMember :exec
update session_members
set is_deleted = true, is_admin = false
where session_id = $1 and member_id = $2
`

type DeleteSessionMemberParams struct {
	SessionID uuid.UUID
	MemberID  uuid.UUID
}

func (q *Queries) DeleteSessionMember(ctx context.Context, arg DeleteSessionMemberParams) error {
	_, err := q.db.ExecContext(ctx, deleteSessionMember, arg.SessionID, arg.MemberID)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
select s.id, s.name, s.is_active, s.created_at, s.updated_at, coalesce(sum(l.amount), 0)::float8 as total
from sessions s
left join session_transactions t on s.id = t.session_id
left join session_transaction_lines l on t.id = l.transaction_id
where s.id = $1
group by s.id, s.name, s.is_active, s.created_at, s.updated_at
`

type GetSessionByIDRow struct {
	ID        uuid.UUID
	Name      string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
	Total     float64
}

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (GetSessionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i GetSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Total,
	)
	return i, err
}

const getSessionHistory = `-- name: GetSessionHistory :many
select id, session_id, member_id, event_type, event_data, created_at from session_history where session_id = $1
`

func (q *Queries) GetSessionHistory(ctx context.Context, sessionID uuid.UUID) ([]SessionHistory, error) {
	rows, err := q.db.QueryContext(ctx, getSessionHistory, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionHistory
	for rows.Next() {
		var i SessionHistory
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.MemberID,
			&i.EventType,
			&i.EventData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionMember = `-- name: GetSessionMember :one
select u.id, u.username, u.name, u.created_at, u.updated_at, sm.is_admin
from users u
join session_members sm on u.id = sm.member_id
where sm.session_id = $1 and u.id = $2
`

type GetSessionMemberParams struct {
	SessionID uuid.UUID
	ID        uuid.UUID
}

type GetSessionMemberRow struct {
	ID        uuid.UUID
	Username  string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	IsAdmin   bool
}

func (q *Queries) GetSessionMember(ctx context.Context, arg GetSessionMemberParams) (GetSessionMemberRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionMember, arg.SessionID, arg.ID)
	var i GetSessionMemberRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const getSessionTransactionLines = `-- name: GetSessionTransactionLines :many
select
    t.id as transaction_id,
    t.session_id,
    t.member_id as creator_id,
    t.created_at,
    tl.member_id,
    tl.amount::float8 as amount
from session_transactions t
join session_transaction_lines tl on t.id = tl.transaction_id
where t.session_id = $1
`

type GetSessionTransactionLinesRow struct {
	TransactionID uuid.UUID
	SessionID     uuid.UUID
	CreatorID     uuid.UUID
	CreatedAt     time.Time
	MemberID      uuid.UUID
	Amount        float64
}

func (q *Queries) GetSessionTransactionLines(ctx context.Context, sessionID uuid.UUID) ([]GetSessionTransactionLinesRow, error) {
	rows, err := q.db.QueryContext(ctx, getSessionTransactionLines, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSessionTransactionLinesRow
	for rows.Next() {
		var i GetSessionTransactionLinesRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.SessionID,
			&i.CreatorID,
			&i.CreatedAt,
			&i.MemberID,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionMembers = `-- name: ListSessionMembers :many
select u.id, u.username, u.name, u.created_at, u.updated_at, sm.is_admin, sm.is_deleted
from users u
join session_members sm on u.id = sm.member_id
where sm.session_id = $1
`

type ListSessionMembersRow struct {
	ID        uuid.UUID
	Username  string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	IsAdmin   bool
	IsDeleted bool
}

func (q *Queries) ListSessionMembers(ctx context.Context, sessionID uuid.UUID) ([]ListSessionMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionMembers, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionMembersRow
	for rows.Next() {
		var i ListSessionMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsAdmin,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsForUser = `-- name: ListSessionsForUser :many
with user_sessions as (
    select
        s.id,
        s.name,
        s.is_active,
        s.created_at,
        s.updated_at,
        coalesce(sum(tl.amount), 0)::float8 as total_amount
    from sessions s
        join session_members sm_target on s.id = sm_target.session_id
        left join session_transactions t on s.id = t.session_id
        left join session_transaction_lines tl on t.id = tl.transaction_id
    where sm_target.member_id = $1
      and sm_target.is_deleted = false
    group by s.id, s.name, s.is_active, s.created_at, s.updated_at
    order by s.updated_at desc, s.id desc
    limit nullif($2, 0)
)
select
    st.id, st.name, st.is_active, st.created_at, st.updated_at, st.total_amount,
    m.id as member_id,
    m.name as member_name,
    m.username as member_username
from user_sessions st
join session_members sm on st.id = sm.session_id
join users m on sm.member_id = m.id
order by st.updated_at desc, st.id desc
`

type ListSessionsForUserParams struct {
	MemberID uuid.UUID
	Column2  interface{}
}

type ListSessionsForUserRow struct {
	ID             uuid.UUID
	Name           string
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	TotalAmount    float64
	MemberID       uuid.UUID
	MemberName     string
	MemberUsername string
}

func (q *Queries) ListSessionsForUser(ctx context.Context, arg ListSessionsForUserParams) ([]ListSessionsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsForUser, arg.MemberID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsForUserRow
	for rows.Next() {
		var i ListSessionsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalAmount,
			&i.MemberID,
			&i.MemberName,
			&i.MemberUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionExists = `-- name: SessionExists :one
select exists(select 1 from sessions where id = $1)
`

func (q *Queries) SessionExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, sessionExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setSessionUpdatedNow = `-- name: SetSessionUpdatedNow :exec
update sessions set updated_at = now() where id = $1
`

func (q *Queries) SetSessionUpdatedNow(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setSessionUpdatedNow, id)
	return err
}

const updateSessionActiveState = `-- name: UpdateSessionActiveState :exec
update sessions set is_active = $2 where id = $1
`

type UpdateSessionActiveStateParams struct {
	ID       uuid.UUID
	IsActive bool
}

func (q *Queries) UpdateSessionActiveState(ctx context.Context, arg UpdateSessionActiveStateParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionActiveState, arg.ID, arg.IsActive)
	return err
}

const updateSessionMemberAdminState = `-- name: UpdateSessionMemberAdminState :exec
update session_members
set is_admin = $3
where session_id = $1 and member_id = $2
`

type UpdateSessionMemberAdminStateParams struct {
	SessionID uuid.UUID
	MemberID  uuid.UUID
	IsAdmin   bool
}

func (q *Queries) UpdateSessionMemberAdminState(ctx context.Context, arg UpdateSessionMemberAdminStateParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionMemberAdminState, arg.SessionID, arg.MemberID, arg.IsAdmin)
	return err
}
