### Get Friends
GET {{base_url}}/api/friends

### Get Friend By ID
GET {{base_url}}/api/friend/116bf296-7b02-425a-b8db-3cd1c31d3b7d

### Get joint sessions with friend by ID
GET {{base_url}}/api/friend/116bf296-7b02-425a-b8db-3cd1c31d3b7d/sessions
