### Sign up
POST {{base_url}}/api/auth/signup
Content-Type: application/json

{
  "name": "User Name",
  "username": "user-1",
  "password": "password",
  "verificationPassword": "password"
}

### Login
POST {{base_url}}/api/auth/login
Content-Type: application/json

{
  "username": "mike",
  "password": "password"
}

### Logout
POST {{base_url}}/api/auth/logout

### Refresh JWT
POST {{base_url}}/api/auth/refresh

### Initialize Password Reset
POST {{base_url}}/api/auth/password/initialize-reset
Content-Type: application/json

{
  "password": "password"
}

### Reset Password
POST {{base_url}}/api/auth/password/reset
Content-Type: application/json

{
  "otp": "g6wfuo"
}

