// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package history

import (
	"time"
)

type Member struct {
	ID        string
	Name      string
	Username  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Session struct {
	ID        string
	Name      string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SessionHistory struct {
	ID        int64
	SessionID string
	MemberID  string
	EventType string
	EventData []byte
	CreatedAt time.Time
}

type SessionMember struct {
	SessionID string
	MemberID  string
	IsOwner   bool
	IsAdmin   bool
	IsDeleted bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Transaction struct {
	ID        string
	SessionID string
	MemberID  string
	CreatedAt time.Time
}

type TransactionLine struct {
	TransactionID string
	MemberID      string
	Amount        float64
}
