// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user-ledger-queries.sql

package ledger

import (
	"context"
)

const insertUserLedger = `-- name: InsertUserLedger :exec
insert into user_ledger (user_id, participant_id, amount, type)
values (?1, ?2, ?3, case when ?3 < 0 then 'debit' else 'credit' end)
`

type InsertUserLedgerParams struct {
	UserID        string
	ParticipantID string
	Amount        float64
}

func (q *Queries) InsertUserLedger(ctx context.Context, arg InsertUserLedgerParams) error {
	_, err := q.db.ExecContext(ctx, insertUserLedger, arg.UserID, arg.ParticipantID, arg.Amount)
	return err
}
