// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: ledger-queries.sql

package ledger

import (
	"context"
)

const insertLedger = `-- name: InsertLedger :exec
insert into ledger (id, transaction_id, session_id, user_id, amount)
values (?, ?, ?, ?, ?)
`

type InsertLedgerParams struct {
	ID            string
	TransactionID string
	SessionID     string
	UserID        string
	Amount        float64
}

func (q *Queries) InsertLedger(ctx context.Context, arg InsertLedgerParams) error {
	_, err := q.db.ExecContext(ctx, insertLedger,
		arg.ID,
		arg.TransactionID,
		arg.SessionID,
		arg.UserID,
		arg.Amount,
	)
	return err
}
