// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package ledger

import (
	"time"
)

type Ledger struct {
	ID            string
	TransactionID string
	SessionID     string
	UserID        string
	Amount        float64
	CreatedAt     time.Time
}
