// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package session

import (
	"time"
)

type Session struct {
	ID        string
	Name      string
	OwnerID   string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SessionMember struct {
	SessionID string
	UserID    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserDetail struct {
	ID       string
	Username string
}
