// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user-queries.sql

package user

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
insert into users (id, username, bio) values (?, ?, ?)
returning id, username, bio, balance, created_at, updated_at
`

type CreateUserParams struct {
	ID       string
	Username string
	Bio      sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ID, arg.Username, arg.Bio)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Bio,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
select id, username, bio, balance, created_at, updated_at from users where id = ? limit 1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Bio,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
update users
set username = ?, bio = ? where id = ?
returning id, username, bio, balance, created_at, updated_at
`

type UpdateUserParams struct {
	Username string
	Bio      sql.NullString
	ID       string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.Username, arg.Bio, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Bio,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
