// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package auth

import (
	"time"
)

type RefreshToken struct {
	ID          int64
	UserID      string
	HashedToken string
	ExpiresAt   time.Time
	Revoked     bool
	CreatedAt   time.Time
}

type User struct {
	ID             string
	Username       string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
