-- +goose Up
-- +goose StatementBegin
create table if not exists session_history (
    id integer primary key generated by default as identity,
    session_id uuid not null references sessions(id) on delete cascade,
    member_id uuid not null references users(id) on delete no action,
    event_type text not null,
    event_data jsonb,
    created_at timestamp with time zone not null default now()
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
drop table if exists session_history;
-- +goose StatementEnd
