// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Ledger struct {
	ID            uuid.UUID
	TransactionID uuid.UUID
	UserID        uuid.UUID
	Amount        string
	CreatedAt     time.Time
}

type RefreshToken struct {
	ID          int32
	UserID      uuid.UUID
	HashedToken string
	ExpiresAt   time.Time
	Revoked     bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Session struct {
	ID        uuid.UUID
	Name      string
	IsActive  bool
	CreatorID uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SessionHistory struct {
	ID        int32
	SessionID uuid.UUID
	MemberID  uuid.UUID
	EventType string
	EventData pqtype.NullRawMessage
	CreatedAt time.Time
}

type SessionMember struct {
	SessionID uuid.UUID
	MemberID  uuid.UUID
	IsAdmin   bool
	IsDeleted bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SessionTransaction struct {
	ID        uuid.UUID
	SessionID uuid.UUID
	MemberID  uuid.UUID
	CreatedAt time.Time
}

type SessionTransactionLine struct {
	TransactionID uuid.UUID
	MemberID      uuid.UUID
	Amount        string
}

type User struct {
	ID                        uuid.UUID
	Username                  string
	Email                     string
	UpdateEmail               sql.NullString
	EmailUpdateRequestedAt    sql.NullTime
	EmailUpdateOtp            sql.NullString
	EmailLastUpdatedAt        sql.NullTime
	Name                      string
	HashedPassword            string
	UpdateHashedPassword      sql.NullString
	PasswordUpdateRequestedAt sql.NullTime
	PasswordUpdateOtp         sql.NullString
	PasswordLastUpdatedAt     sql.NullTime
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
}

type UserCreditScore struct {
	UserID                uuid.UUID
	BeersGiven            int64
	BeersReceived         int64
	BalanceRatio          string
	AvgReciprocationRatio string
	RecentGiving          string
	CreditScore           int32
	StatusLabel           string
}

type UserTotal struct {
	UserID uuid.UUID
	Credit string
	Debit  string
}
