name: CI Test

on:
  push:
    branches: [main]
  pull_request:
      branches: [main]

jobs:
  session-service-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24

    - name: Install dependencies
      run: go mod tidy
      working-directory: ./session-service

    - name: Run tests
      run: go test ./... -v
      working-directory: ./session-service

  user-service-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Install dependencies
        run: go mod tidy
        working-directory: ./user-service

      - name: Run tests
        run: go test ./... -v
        working-directory: ./user-service

  transaction-service-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Install dependencies
        run: go mod tidy
        working-directory: ./transaction-service

      - name: Run tests
        run: go test ./... -v
        working-directory: ./transaction-service

  ledger-service-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Install dependencies
        run: go mod tidy
        working-directory: ./ledger-service

      - name: Run tests
        run: go test ./... -v
        working-directory: ./ledger-service

  auth-service-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Install dependencies
        run: go mod tidy
        working-directory: ./auth-service

      - name: Run tests
        run: go test ./... -v
        working-directory: ./auth-service
